### ISSUE TITLE
Scorm player

### ISSUE THREAD

**Issue by gheeenrique** [pipwerks/scorm-api-wrapper#38] opened 2017-10-20 00:26 UTC
I'm trying to develop a scorm player that sends to mysql, has anyone done anything like this? Thank you.

**Comment by pipwerks** [comment] 2017-10-21 23:35
No offense but this area is for reporting issues with the wrapper. Closing, as this is not a bug report or feature request.

**Closed by pipwerks** 2017-10-21 23:35 UTC
