### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by nathanqueija** [pipwerks/scorm-api-wrapper#31] opened 2017-05-29 14:39 UTC
Do you have any tutorials how to use this api?
THanks

**Comment by grpaiva** [comment] 2017-06-02 14:07
First of all: this is freaking awesome! I'm CTO at an online school and we'll need to create SCORM packages of some of our courses. Tried captivate (yikes) and then this beautiful wrapper.

**Comment by grpaiva** [comment] 2017-06-02 20:21
Actually, this documentation here is helping me a lot:

[https://pipwerks.com/laboratory/scorm/api-wrapper-javascript/](https://pipwerks.com/laboratory/scorm/api-wrapper-javascript/)

**Comment by grpaiva** [comment] 2017-06-07 13:57
@nathanqueija Just for the record. Using pipwerk's `pipwerks.SCORM.get()`, `pipwerks.SCORM.set()` and `pipwerks.SCORM.save()` you can do pretty much everything based on [SCORM'S Run-time reference](https://scorm.com/scorm-explained/technical-scorm/run-time/run-time-reference/). For example, getting and setting `lesson_location`:

```
this.scorm = pipwerks.SCORM; // shortcut

this.scorm.version = "1.2";
      
if(this.scorm.init()){

    var location = this.scorm.get("cmi.core.lesson_location");
 
    if(location !== ""){
        console.log(location);
        // do something with previous location
    }

    this.scorm.set('cmi.core.lesson_location', 'anything you want to set as location');

    this.scorm.save();
}

```

**Comment by Heffiros** [comment] 2017-09-13 09:51
Hello

I have to do some test with this wrapper and i have some question.
We have a SCORM module that is not in a LMS but we need to communicate with it. When i try to use your demo file i have some mistakes  : 

SCORM.API.find: SCORM version 1.2 was specified by user, but API cannot be found.
SCORM.API.find: Error finding API. 
Find attempts: 0. 
Find attempt limit: 500
API.get failed: Can't find the AP  

So do I have to recode this API if I have a SCORM module without a LMS to play?

Thanx for your answer

**Comment by atmonello** [comment] 2018-03-14 18:43
You guys had any luck using this API? I have followed this guide found on **Pipwerks** site:
[https://pipwerks.com/2008/05/08/adding-scorm-code-to-an-html-file/](https://pipwerks.com/2008/05/08/adding-scorm-code-to-an-html-file/)

But it doesn't seem to work. When I open my HTML file on the browser, it's not even giving any errors (it _should_ alert that it can't connect to the LMS), and trying to run it into SCORM Cloud just leads to a blank page (page title says _"Page not found"_, but I'm _not even_ redirecting the course to any other page).

Any help would be greatly appreciated!

(And BTW, 100% brazilians on this issue! 😄)

**Comment by pipwerks** [comment] 2018-04-14 03:40
This is not a bug report, closing issue

**Closed by pipwerks** 2018-04-14 03:40 UTC

**Comment by yinjingjiu** [comment] 2018-07-03 02:22
@grpaiva Can you upload your example? Thanks
