### ISSUE TITLE
Add NPM support

### ISSUE THREAD

**Issue by mauro1998** [pipwerks/scorm-api-wrapper#35] opened 2017-08-24 16:43 UTC
Hi there,
Thanks for the great API wrapper.
It would be great if the javascript plugin were available as a NPM package.

**Comment by pipwerks** [comment] 2017-08-24 19:27
Duplicate of https://github.com/pipwerks/scorm-api-wrapper/issues/33

**Closed by pipwerks** 2017-08-24 19:27 UTC
